"""Hand-authored scorer specification: phase bands + predicate templates.

The *semantics* live here; the *numbers* live in ``data/scorer_calibration.json``
(generated by ``scripts/calibrate_scorer.py`` with the rule documented in
``src/scorer/calibration.py``). Keeping them apart means the calibration can be
regenerated without touching the wrestling reasoning, and vice versa.

Per predicate: ``(feature, kind, weight)`` with
``kind in {band, at_most, at_least, ang_near}`` (see ``membership.py``).
Weights: 2.0 = technique-defining relationship (MISSION.md "Preserve wrestling
geometry"), 1.0 = supporting context.

``executor`` records which reference robot demonstrates the technique
(A = attacker/recoverer, B = defender/opponent; data/refs roles per notes.md).

Phase bands: keyframe-index bands of the phase-2 references. Keyframe times
were reconstructed as ``build_technique_targets(tech).times *
time_stretch_requested * time_stretch_kinematic`` (both stretches from the npz
meta) and mapped onto the 50 Hz frame grid; each band ends on the reconstructed
time of its edge's last keyframe — re-verified by scripts/calibrate_scorer.py.
SPRAWL is a montage of three defender sprawl cycles spliced onto the attacker's
shot frames; its per-edge boundaries are blurred by the junction alignment, so
its band boundaries sit on the defender's own trajectories (hip/knee height,
leg-back): 1/3/5 are the three hips-down sprawl windows, 2/4 the rising
recoveries, 0 the standing entry. SPRAWL's sprawl and recover phases share one
template each but hold their own calibrated numbers per band.
"""

from __future__ import annotations

#: sprawl window template: legs shot back, hips low, chest driven through
_SPRAWL_T = [
    ("leg_back_s", "at_most", 2.0),
    ("knee_z_s", "at_most", 2.0),
    ("pitch_s", "at_least", 2.0),
    ("head_chest", "at_most", 1.0),
    ("chest_on", "at_most", 1.0),
]
#: sprawl recovery template: rising, feet coming back under the hips
_SPRAWL_RECOVER_T = [
    ("knee_z_s", "at_least", 2.0),
    ("leg_back_s", "at_least", 2.0),
    ("pitch_s", "band", 1.0),
    ("head_chest", "band", 1.0),
]

TECHNIQUE_SPEC: dict[str, dict] = {
    "DOUBLE_LEG": {
        "executor": "A",
        # keyframes 8; edges t1144/1147/1141/1140 = setup, penetrate, drive, land
        "phases": [("SETUP", 0.0, 0.46), ("PENETRATE", 0.46, 1.34),
                   ("DRIVE", 1.34, 2.22), ("LAND", 2.22, 3.10)],
        "templates": {
            0: [  # standing square, level starts to drop
                ("sep", "band", 1.0),
                ("bearing", "band", 1.0),
                ("knee_z_s", "band", 1.0),
                ("pitch_s", "band", 1.0),
                ("base_w_s", "band", 1.0),
                ("head_rel", "band", 1.0),
            ],
            1: [  # penetration step: depth taken, head to chest, knee UP
                ("sep", "band", 2.0),
                ("dx", "band", 2.0),
                ("head_rel", "at_most", 2.0),
                ("pitch_s", "band", 1.0),
                ("knee_z_s", "at_least", 1.0),
                ("lock_l", "at_most", 1.0),
                ("lock_r", "at_most", 1.0),
            ],
            2: [  # BOTH legs locked behind the thigh/knee, head up-chest
                ("lock_l", "at_most", 2.0),
                ("lock_r", "at_most", 2.0),
                ("lock_asym", "at_most", 2.0),
                ("head_rel", "band", 1.0),
                ("sep", "band", 1.0),
                ("pitch_s", "band", 1.0),
                ("leg_back_s", "band", 1.0),
            ],
            3: [  # finish: opponent's feet come up, drive through
                ("ankle_z_o", "at_least", 2.0),
                ("lock_asym", "at_most", 1.0),
                ("lock_l", "at_most", 1.0),
                ("lock_r", "at_most", 1.0),
                ("knee_z_s", "at_most", 1.0),
                ("sep", "band", 1.0),
                ("dx", "band", 1.0),
            ],
        },
    },

    "SINGLE_LEG": {
        "executor": "A",
        # keyframes 13; edges t978/1001/1094 = setup, capture, finish (2 bands)
        "phases": [("SETUP", 0.0, 1.10), ("CAPTURE", 1.10, 1.90),
                   ("FINISH1", 1.90, 3.52), ("FINISH2", 3.52, 4.60)],
        "templates": {
            0: [  # wide stagger, angled entry
                ("base_w_s", "at_least", 2.0),
                ("bearing", "band", 1.0),
                ("sep", "band", 1.0),
                ("knee_z_s", "band", 1.0),
                ("rel_yaw", "ang_near", 1.0),
            ],
            1: [  # ONE leg captured, head on chest, other leg free
                ("lock_r", "at_most", 2.0),
                ("lock_l", "at_least", 2.0),
                ("lock_asym", "at_least", 2.0),
                ("head_rel", "band", 2.0),
                ("pitch_s", "band", 1.0),
                ("knee_z_s", "at_least", 1.0),
                ("sep", "band", 1.0),
            ],
            2: [  # standing finish: same leg still captured, free leg clear
                ("lock_r", "at_most", 2.0),
                ("lock_asym", "at_least", 2.0),
                ("lock_l", "at_least", 2.0),
                ("head_chest", "at_most", 2.0),
                ("pitch_s", "band", 1.0),
                ("sep", "band", 1.0),
                ("knee_z_s", "band", 1.0),
                ("leg_back_s", "band", 1.0),
            ],
            3: [  # down on the knee, angled off to the side
                ("knee_z_s", "at_most", 2.0),
                ("lock_r", "at_most", 2.0),
                ("lock_l", "at_least", 2.0),
                ("pitch_s", "at_least", 1.0),
                ("roll_s", "band", 1.0),
                ("dz", "at_most", 1.0),
                ("bearing", "band", 1.0),
            ],
        },
    },

    "BODY_LOCK": {
        "executor": "A",
        # single edge t1133 (10 kf): clinch, drop-over, pin
        "phases": [("CLINCH", 0.0, 1.58), ("DROPOVER", 1.58, 2.74),
                   ("PIN", 2.74, 3.52)],
        "templates": {
            0: [  # chest-to-chest lock, arms around, both standing
                ("sep", "at_most", 2.0),
                ("wrap", "at_most", 2.0),
                ("chest_on", "at_most", 1.0),
                ("lock_asym", "at_most", 1.0),
                ("pitch_s", "band", 1.0),
                ("knee_z_s", "at_least", 1.0),
            ],
            1: [  # sweeping drop: lock kept, opponent's balance broken
                ("wrap", "at_most", 2.0),
                ("lock_r", "at_most", 1.0),
                ("lock_l", "at_most", 1.0),
                ("sep", "band", 1.0),
                ("pitch_s", "band", 1.0),
                ("dz", "band", 1.0),
                ("ankle_z_o", "band", 1.0),
            ],
            2: [  # opponent driven down at the hip, feet off the mat
                ("dz", "at_most", 2.0),
                ("ankle_z_o", "at_least", 2.0),
                ("roll_s", "at_least", 1.0),
                ("pitch_s", "at_least", 1.0),
                ("sep", "band", 1.0),
                ("knee_z_s", "band", 1.0),
                ("wrap", "at_most", 1.0),
            ],
        },
    },

    "SNAPDOWN": {
        "executor": "A",
        # single edge t989 (3 kf): collar tie, snap
        "phases": [("SETUP", 0.0, 0.46), ("SNAP", 0.46, 0.92)],
        "templates": {
            0: [  # collar+tricep tie, opponent upright
                ("head_snap", "at_most", 2.0),
                ("sep", "band", 1.0),
                ("pitch_o", "band", 1.0),
                ("knee_z_s", "band", 1.0),
                ("head_rel", "band", 1.0),
                ("wrap", "at_most", 1.0),
            ],
            1: [  # head yanked down: opponent pitches forward, feet planted
                ("head_snap", "at_most", 2.0),
                ("pitch_o", "at_least", 2.0),
                ("pitch_s", "band", 1.0),
                ("sep", "band", 1.0),
                ("ankle_z_o", "at_most", 1.0),
                ("knee_z_s", "at_most", 1.0),
            ],
        },
    },

    "SPRAWL": {
        "executor": "B",
        "phases": [("STAND1", 0.0, 1.80), ("SPRAWL1", 1.80, 2.64),
                   ("RECOVER1", 2.64, 3.36), ("SPRAWL2", 3.36, 4.32),
                   ("RECOVER2", 4.32, 5.28), ("SPRAWL3", 5.28, 5.76)],
        "templates": {
            0: [  # still standing, feet under hips, chest closing on the shot
                ("knee_z_s", "at_least", 2.0),
                ("leg_back_s", "band", 2.0),
                ("pitch_s", "at_most", 1.0),
                ("chest_on", "band", 1.0),
                ("ankle_z_s", "band", 1.0),
            ],
            1: _SPRAWL_T, 3: _SPRAWL_T, 5: _SPRAWL_T,
            2: _SPRAWL_RECOVER_T, 4: _SPRAWL_RECOVER_T,
        },
    },

    "STAND_UP": {
        "executor": "A",
        # montage t952/t1110/t1125; bands on reconstructed keyframe times
        "phases": [("DOWN", 0.0, 2.00), ("STAND1", 2.00, 3.96),
                   ("STAND2", 3.96, 6.94), ("CLINCH", 6.94, 9.38)],
        "templates": {
            0: [  # from knees/hands: knees low, feet pulled forward
                ("knee_z_s", "at_most", 2.0),
                ("ankle_z_s", "at_most", 2.0),
                ("leg_back_s", "at_least", 1.0),
                ("base_w_s", "at_most", 1.0),
                ("chest_on", "band", 1.0),
                ("head_chest", "at_most", 1.0),
            ],
            1: [  # first stand-up: rising through knee-high
                ("knee_z_s", "band", 2.0),
                ("ankle_z_s", "band", 1.0),
                ("pitch_s", "band", 1.0),
                ("head_chest", "at_most", 1.0),
                ("sep", "band", 1.0),
            ],
            2: [  # technical stand-up cycle: mid knees, feet narrow->rise
                ("knee_z_s", "band", 2.0),
                ("ankle_z_s", "band", 1.0),
                ("leg_back_s", "band", 1.0),
                ("chest_on", "band", 1.0),
                ("head_chest", "at_most", 1.0),
            ],
            3: [  # dogfight clinch: fully up, deep underhook, glued
                ("knee_z_s", "at_least", 2.0),
                ("ankle_z_s", "at_least", 2.0),
                ("wrap", "at_most", 2.0),
                ("chest_on", "at_most", 2.0),
                ("head_chest", "at_most", 1.0),
                ("sep", "band", 1.0),
            ],
        },
    },

    "STANCE": {
        "executor": "A",
        # procedural hold (node 94 blend, 65/35 with the G1 stand pose)
        "phases": [("HOLD", 0.0, 2.34)],
        "templates": {
            0: [
                ("sep", "band", 2.0),
                ("rel_yaw", "ang_near", 2.0),
                ("knee_z_s", "band", 2.0),
                ("pitch_s", "band", 1.0),
                ("base_w_s", "band", 1.0),
                ("lock_l", "at_least", 1.0),
                ("ankle_z_s", "band", 1.0),
                ("head_rel", "band", 1.0),
            ],
        },
    },
}

TECHNIQUES: tuple[str, ...] = tuple(TECHNIQUE_SPEC)
