"""Wrestling environment package (Phase 4).

Modules:
  backdet : back-to-mat detector (deliverable 10)
  env     : two-G1 standing-wrestling environment with exchange loop (deliverable 11)
"""

from .backdet import (
    ROBOTS,
    BackDetConfig,
    BackFeatures,
    BackToMatDetector,
    back_features,
    confirmed_mask,
    first_confirmed_index,
)
from .env import (
    AMBIGUITY_WINDOW_S,
    CONTROL_HZ,
    CONTROL_HZ as CTRL_HZ,
    EXCHANGE_TIMEOUT,
    MAT_RADIUS,
    MATCH_CLOCK,
    N_JOINTS,
    OBS_DIM,
    OOB_EVENTS_TO_FORFEIT,
    QPOS_SLICE,
    STEP_DT,
    ExchangeRecord,
    ReferenceReplay,
    StandHold,
    WrestlingEnv,
    default_observation,
    default_reward,
    keyframe_pair_qpos,
    load_wrestling_model,
    obs_layout,
    reference_trace,
    resolve_back_events,
    stance_start_qpos,
)

__all__ = [
    "ROBOTS",
    "BackDetConfig",
    "BackFeatures",
    "BackToMatDetector",
    "back_features",
    "body_maps",
    "confirmed_mask",
    "first_confirmed_index",
    "AMBIGUITY_WINDOW_S",
    "CONTROL_HZ",
    "CTRL_HZ",
    "EXCHANGE_TIMEOUT",
    "MAT_RADIUS",
    "MATCH_CLOCK",
    "N_JOINTS",
    "OBS_DIM",
    "OOB_EVENTS_TO_FORFEIT",
    "QPOS_SLICE",
    "STEP_DT",
    "ExchangeRecord",
    "ReferenceReplay",
    "StandHold",
    "WrestlingEnv",
    "default_observation",
    "default_reward",
    "keyframe_pair_qpos",
    "load_wrestling_model",
    "obs_layout",
    "reference_trace",
    "resolve_back_events",
    "stance_start_qpos",
]
