export const meta = {
  name: 'phase3_teacher',
  description: 'Phase 3 wave A: stabilized teacher controller + technique-validity scorer v1',
};

const COMMON = [
  'You are a subagent in repo /home/ubuntu/grappling (your cwd).',
  'Read AGENTS.md, goal.md, docs/MISSION.md (relevant sections), docs/CURRICULUM.md,',
  'notes.md (Interface contracts + Phase 2 results), reports/2026-10-07/retarget.md.',
  'Stack: .venv (mujoco 3.15, numpy, scipy, torch-cpu, imageio), MUJOCO_GL=egl headless,',
  'ALWAYS renderer.close(). 4-core ARM CPU — keep runtimes bounded (minutes, not hours).',
  'Assets: robots/wrestling_scene.xml (two G1s, prefixes a_/b_, qpos [0:36]/[36:72],',
  '58 position actuators, kp=500); data/refs/<TECH>.npz (qpos_a, qpos_b, t @50 Hz,',
  'meta with repairs; contract in notes.md). Tests must stay green:',
  '.venv/bin/python -m pytest tests/ -q (currently 30 passed).',
  'Do not modify: goal.md, third_party/, robots/g1/g1.xml, data/refs (read-only),',
  'or base scene physics (derived scene copies allowed, documented).',
  'Report: reports/2026-10-08/<your-name>.md. Append verified FACTS to notes.md.',
  'Final message: metrics table + deliverable paths + honest failures.',
].join('\n');

const TEACHER_TASK = COMMON + '\n\n' + [
  'TASK: Build the STABILIZED TEACHER controller that executes the reference',
  'techniques in simulation WITHOUT falling — closing the documented Phase-2 gap',
  '(pure joint-PD topples: pelvis zErr 0.29-0.83 m on all 7 techniques).',
  '',
  'CONTEXT (verified): references are kinematically valid (joint err <=0.06 rad,',
  'landmark RMS 0.03-0.09 m) but robots sag because position servos alone cannot',
  'balance leaned wrestling postures. The teacher adds feedback on top of',
  'reference joint targets. MISSION teacher spec: state + reference + opponent',
  'state -> teacher joint target (PD/impedance/optimizer). It must be executable',
  'by the 29 position actuators per robot (no root actuation, no privileged forces).',
  '',
  'STABILIZER candidates to implement and evaluate IN ORDER (measure, keep what works):',
  '1. Ankle/hip strategy: torso tilt (pitch/roll vs gravity) + CoM horizontal error',
  '   feedback -> additive offsets on ankle_pitch/hip_pitch (and knee/ankle chain',
  '   to keep foot planted), gains scheduled by phase.',
  '2. Capture-point-ish damping: CoM velocity feedback -> hip pitch/ankle offsets.',
  '3. Foot-anchoring IK correction: when reference foot is planted, re-solve that',
  '   leg to keep the foot at its reference world position (small analytic 6-DoF',
  '   leg IK, G1 legs are 6-DoF chains).',
  '4. Pelvis-height PI on both legs (squat support) for level-change phases.',
  'Compose per-technique, per-phase (phase = keyframe index segments from npz meta).',
  '',
  'EVALUATION (scripts/run_teacher.py, all 7 techniques, >=5 seeds each, 50 Hz ctrl):',
  '- stay_up_frac: fraction of frames where ref pelvis >=0.45 m AND sim pelvis',
  '  >=0.45 m and tilt <30 deg (exclude prone-by-design SPRAWL defender tail).',
  '- final_landmark_dist vs reference end pose (weighted, like Phase 2).',
  '- inter/self/ground penetration.',
  'ACCEPTANCE: stay_up_frac >=0.80 for DOUBLE_LEG, SINGLE_LEG, SNAPDOWN, STANCE,',
  'STAND_UP (recoverer), BODY_LOCK (or documented best + analysis), SPRAWL both',
  'robots end in intended posture (defender prone, attacker sprawled-on).',
  'Iterate stabilizer design until acceptance or clearly diminishing returns;',
  'log every design iteration (hypothesis -> metric) in the report.',
  '',
  'BODY_LOCK remediation attempt: if inter-penetration still fails, try derived-scene',
  'contact parameter overrides (solref/solimp/margin on torso geoms, copy scene,',
  'document every change) — goal <3 cm residual while keeping techniques working.',
  '',
  'DELIVERABLES: src/teacher/ (controller + stabilizers + phase tables),',
  'scripts/run_teacher.py, data/teacher_stats.json, videos/teacher/<TECH>.mp4',
  '(30 fps, both robots — these must visibly show robots STAYING UP vs the',
  'Phase-2 videos), tests/test_teacher.py (controller invariants: targets within',
  'ctrlrange, deterministic, phase monotonic). Report with iteration log.',
].join('\n');

const SCORER_TASK = COMMON + '\n\n' + [
  'TASK: Build TECHNIQUE-VALIDITY SCORER v1 (deliverable 7) — a hand-engineered',
  'relational-geometry judge, COMPLETELY SEPARATE from any RL critic (separate',
  'package src/scorer/, never imported by any value-function code).',
  '',
  'PURPOSE (MISSION): detect whether a commanded technique still resembles its',
  'movement family — prevents "reward says double leg but policy runs shoulder-first".',
  'It must NOT be rigid: score conformity of RELATIONSHIPS, allow adaptation.',
  '',
  'DESIGN: score(technique, phase, self_qpos, opp_qpos, model) -> float [0,1] plus',
  'per-term breakdown. Per technique, per phase segment (keyframe index bands from',
  'data/refs meta), relational predicates from MISSION "Preserve wrestling geometry":',
  '- pelvis-pelvis vector (attack depth, drive direction)',
  '- torso pitch/roll of both robots',
  '- head position relative to opponent pelvis (head-on-chest etc.)',
  '- knee/ankle heights (level change, sprawl depth, standing recovery)',
  '- hand/wrist proximity to opponent leg/torso (double/single lock points)',
  '- base width / support configuration',
  'Each predicate = fuzzy membership (smooth, documented thresholds calibrated ON',
  'the reference data: reference frames must score ~1.0 on their own technique).',
  '',
  'VALIDATION (tests/test_scorer.py):',
  '- every data/refs technique scores >=0.8 mean on ITS OWN trace per phase;',
  '- cross-scores low (e.g. DOUBLE_LEG trace scored as SINGLE_LEG <0.5 mean);',
  '- perturbation monotonicity: adding increasing deviation (joint noise, root',
  '  tilt, phase shift) to a reference trace monotonically decreases score;',
  '- speed: <1 ms per call on this CPU (it will run inside training loops).',
  '',
  'DELIVERABLES: src/scorer/__init__.py (+ modules), tests, a calibration report',
  'table (per technique/phase thresholds chosen + why), reports/2026-10-08/scorer.md.',
  'Add scripts/score_trace.py: scores any data/refs npz trace, prints table.',
].join('\n');

log('Phase 3A: TeacherBuilder + ScorerV1 (parallel)');

const results = await parallel([
  () => agent(TEACHER_TASK, { name: 'TeacherBuilder', model: 'opencode-go/deepseek-v4.1-flash' }),
  () => agent(SCORER_TASK, { name: 'ScorerV1', model: 'opencode-go/deepseek-v4.1-flash' }),
]);

log('Phase 3A complete');

return {
  teacher_summary: String(results[0]).slice(0, 2500),
  scorer_summary: String(results[1]).slice(0, 2000),
};
